import localFont from "next/font/local";
import "./globals.css";



export const metadata = {
  title: "Wunmi's Kitchen",
  description: "Generated by Adewuyi Fawaz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
